version: '3.8'

services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - microservices-network
    restart: unless-stopped
    volumes:
      - loki-data:/loki

volumes:
  loki-data:
    driver: local

networks:
  microservices-network:
    external: true
