apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    access: proxy
    url: http://otel-collector:4317
    uid: tempo
    isDefault: false
    editable: false
    jsonData:
      httpMethod: GET
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: -10m
        spanEndTimeShift: 10m
        tags: [{ key: 'service.name', value: 'job' }]
        filterByTraceID: true
        filterBySpanID: false
      serviceMap:
        datasourceUid: prometheus
      nodeGraph:
        enabled: true
      search:
        hide: false
      lokiSearch:
        datasourceUid: loki
      spanBar:
        type: 'Tag'
        tag: 'http.status_code'
